### ISSUE TITLE
Game Balance Ideas (edit to change)

### ISSUE THREAD

**Issue by sunmatthew** [ConMur/BindingOfMangat#11]
Player --> 5 hearts to start off

Student Enemy --> takes 2 normal hits to kill
Student Cluster Enemy --> takes 2 normal hits to kill
Einstein Enemy --> takes 1 normal hit to kill
Cell Enemy --> takes 2 normal hits to kill
Chem Enemy --> takes 3 normal hits to kill
Molecule Enemy --> takes 3 normal hits to kill
Eclipse Enemy --> takes 1 normal hit to kill
Gissing --> takes 15 normal hits to kill

**Comment by ConMur** [comment]
looks good
