### ISSUE TITLE
Rooms repeat

### ISSUE THREAD

**Issue by ConMur** [ConMur/BindingOfMangat#5]
Sometimes when going through the same combination of doors, the rooms repeat

**Comment by sunmatthew** [comment]
Also, when going through doors (ex. North to South or East to West) you never actually exit the room and the room seems to loop/wrap around. When this happens the enemies in the room also speed up and they keep speeding up until the program crashes :D

**Comment by ConMur** [comment]
This could be caused by the code that connects doors between two different rooms. Do a check before setting the door to se if the door was not already set

**Comment by ConMur** [comment]
used get instead of remove :pensive:
