### ISSUE TITLE
Things we need to get done by Monday

### ISSUE THREAD

**Issue by sunmatthew** [ConMur/BindingOfMangat#8]
**HIGH PRIORITY**
4. Game balance (priority but should be done last)

**MEDIUM PRIORITY**
1. ~~Implementing key rooms, keys~~, items
2. Polishing enemy projectile and movement behaviour
3. Implementing currency and shops
4. Minimap fog
5. Boss room trapdoor (correct coordinates --> center of room)
6. Boss health bar
7. Sort all room objects by Y-position (prevent overlap)
8. Bosses drop an item

**LOW PRIORITY --> EXTRA**
1. More rock designs
2. Cut scenes and add intro
3. Commenting
4. Enemy specific behaviour
5. Item use

**Comment by ConMur** [comment]
key rooms are now working

**Comment by ConMur** [comment]
also, if you edit the OP, you can use two tildes before and after the sentence to strike through the thing you added/fixed. ~~like this~~

**Comment by ConMur** [comment]
I have enemies spawning on items potentially, will that do anything?

**Comment by ConMur** [comment]
We need a boss for level 2 and 4. If we cant get pictures for them, use thier code but a different boss' image
